spring:
  datasource:
    username: sa
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret:
    key: dlatlzlrkqtdlqfurgkqslek