spring:
  profiles:
    default: local
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret:
    key: ${JWT_KEY}
